name: Lint and Format Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 chosung_translator tests run_train.py run_inference.py
    - name: Check an order of import statements with isort
      run: |
        isort -c chosung_translator tests run_train.py run_inference.py
    - name: Check the code formatting with black
      run: |
        black --check chosung_translator tests run_train.py run_inference.py
